<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
<? foreach ($this->_scripts as $script): ?>
        <script type="text/javascript" src="media/js/<?= $script ?>.js"></script>
<? endforeach; ?>
<? foreach ($this->_styles as $style): ?>
        <link rel="stylesheet" type="text/css" href="media/css/<?= $style ?>.css">
<? endforeach; ?>
    </head>
    <body>
        <?= $this->get('template') ?>

    </body>
</html>
